
package webService.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebService_Server_Impl", targetNamespace = "http://server.webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceServerImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reverseString", targetNamespace = "http://server.webService/", className = "webService.client.ReverseString")
    @ResponseWrapper(localName = "reverseStringResponse", targetNamespace = "http://server.webService/", className = "webService.client.ReverseStringResponse")
    @Action(input = "http://server.webService/WebService_Server_Impl/reverseStringRequest", output = "http://server.webService/WebService_Server_Impl/reverseStringResponse")
    public String reverseString(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "greet", targetNamespace = "http://server.webService/", className = "webService.client.Greet")
    @ResponseWrapper(localName = "greetResponse", targetNamespace = "http://server.webService/", className = "webService.client.GreetResponse")
    @Action(input = "http://server.webService/WebService_Server_Impl/greetRequest", output = "http://server.webService/WebService_Server_Impl/greetResponse")
    public String greet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
